CREATE TABLE [dbo].[COMPRAS]
(
[IDCOM] [int] NOT NULL IDENTITY(1, 1),
[IDPROV] [int] NOT NULL,
[IDEMP] [int] NOT NULL,
[FECCOM] [date] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COMPRAS] ADD CONSTRAINT [COMPRAS_pk] PRIMARY KEY CLUSTERED ([IDCOM]) ON [PRIMARY]
GO
